version: "3.7"
services:
  postgres_db:
    image: postgres
    environment:
      POSTGRES_USER: relay
      POSTGRES_PASSWORD: relay
      POSTGRES_DB: relay
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  web:
    image: relay
    depends_on:
      - postgres_db
    ports:
      - "80:8080"
      - "443:8443"