version: '3.7'
services:
  dev_db:
    container_name: relay_dev_db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_USER=relay
      - POSTGRES_DB=relay
    ports:
      - 5432:5432
  test_db:
    container_name: relay_test_db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=relay_test
      - POSTGRES_USER=relay_test
      - POSTGRES_DB=relay_test
    ports:
      - 5433:5432

volumes:
  relay_dev_db: { }
  relay_test_db: { }
