version: "3.7"
services:
  postgres_db:
    image: postgres
    environment:
      POSTGRES_USER: relay
      POSTGRES_PASSWORD: relay
      POSTGRES_DB: relay
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432