version: "3.7"
services:
  postgres_db:
    image: postgres
    environment:
      POSTGRES_USER: relay
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: relay
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  wireguard:
    container_name: wireguard
    image: linuxserver/wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - SERVERURL=${RELAY_URL}
      - SERVERPORT=${RELAY_WG_PORT}
      - PEERS=deleteMe
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.0.0.0
    ports:
      - ${RELAY_WG_PORT}:${RELAY_WG_PORT}/udp
    volumes:
      - type: bind
        source: ./config/
        target: /config/
      - type: bind
        source: /lib/modules
        target: /lib/modules
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1