#Used for deploy on an E2C instance via Docker-compose
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/relay
    username: relay
    password: ${POSTGRES_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_PROD_CLIENT_ID}
            clientSecret: ${GITHUB_PROD_CLIENT_SECRET}
security:
  require-ssl: true
server:
  port: 443
  ssl:
    enabled: true
    key-store: /etc/letsencrypt/live/${RELAY_URL}/keystore.p12
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    keyStoreType: PKCS12
    keyAlias: tomcat
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  shutdown: graceful