spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/relay
    username: relay
    password: ${POSTGRES_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_DEV_CLIENT_ID}
            clientSecret: ${GITHUB_DEV_CLIENT_SECRET}

relayConfig:
  url: ${RELAY_URL}
  wgPort: ${RELAY_WG_PORT}
  adminUsers: zfz7