spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/relay_test
    username: relay_test
    password: relay_test
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    root: OFF
relayConfig:
  disableLogs: false
  url: example.com
  wgPort: 51820