#Used for deploy on an E2C instance via Docker-compose
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/relay
    username: relay
    password: relay
  jpa:
    hibernate:
      ddl-auto: validate
security:
  require-ssl: true
server:
  port: 443
  ssl:
    enabled: true
    key-store: /etc/letsencrypt/live/relay.zfz7.org/keystore.p12
    key-store-password: relay
    keyStoreType: PKCS12
    keyAlias: tomcat