spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/relay
    username: relay
    password: ${POSTGRES_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
codeService:
  code: ${WG_CODE}