name: Gradle Test

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      relay_db:
        image: postgres
        env:
          POSTGRES_PASSWORD: relay_test
          POSTGRES_USER: relay_test
          POSTGRES_DB: relay_test
        ports:
          - 5433:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run tests
        run: ./gradlew test